name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip lzop
        sudo apt install -y wget lib32z1 lib32stdc++6
        pip3 install --upgrade Cython==0.29.36 virtualenv
        python3 -m virtualenv venv
        source venv/bin/activate
        pip install buildozer

    - name: Build with Buildozer
      run: |
        source venv/bin/activate
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: bin/**/*.apk
