name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Buildozer
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev
        pip install buildozer

    - name: Install Android SDK and NDK
      run: |
        sudo apt-get install -y openjdk-11-jdk
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.3.6528147"

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer init
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: |
          ./*.apk
          .buildozer/android/platform/build/dists/*/bin/*.apk
